use ark_ff::{FftField, Field};

use super::{config::Config, Commitment};
use crate::{
    algebra::{
        dot,
        embedding::Embedding,
        ntt,
        polynomials::{CoefficientList, MultilinearPoint},
        tensor_product, Weights,
    },
    hash::Hash,
    protocols::{
        geometric_challenge::geometric_challenge,
        irs_commit,
        whir::zk::{HelperEvaluations, ZkParams},
    },
    transcript::{
        codecs::U64, Codec, Decoding, DuplexSpongeInterface, ProverMessage, VerificationResult,
        VerifierMessage, VerifierState,
    },
    utils::zip_strict,
    verify,
};

enum RoundCommitment<'a, F: FftField> {
    Initial {
        commitments: &'a [&'a irs_commit::Commitment<F>],
        batching_weights: Vec<F>,
    },
    Round {
        commitment: irs_commit::Commitment<F>,
    },
}

impl<F: FftField> Config<F> {
    /// Verify a batched WHIR proof for multiple commitments.
    ///
    /// This verifies a batch proof generated by `prove_batch`. The verifier reads the N×M
    /// constraint evaluation matrix from the transcript, samples the batching randomness γ,
    /// and reconstructs the combined constraints using RLC. Round 0 verifies openings in all
    /// N original commitment trees, while subsequent rounds verify the single batched polynomial.
    ///
    /// Returns the constraint evaluation point and values of deferred constraints.
    #[allow(clippy::too_many_lines)]
    pub fn verify<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        commitments: &[&Commitment<F>],
        weights: &[&Weights<F>],
        evaluations: &[F],
    ) -> VerificationResult<(MultilinearPoint<F>, Vec<F>)>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
        [u8; 32]: Decoding<[H::U]>,
        U64: Codec<[H::U]>,
        Hash: ProverMessage<[H::U]>,
    {
        let num_polynomials = commitments.len() * self.initial_committer.num_polynomials;
        verify!(weights.len() * num_polynomials == evaluations.len());
        if num_polynomials == 0 {
            return Ok((MultilinearPoint::default(), Vec::new()));
        }

        // Complete the constraint and evaluation matrix with OODs and their cross-terms.
        let (constraint_weights, constraint_matrix) = {
            let mut all_weights = Vec::new();
            let mut matrix = Vec::new();

            // OOD weights from each commitment, evaluated for each polynomial
            let mut polynomial_offset = 0;
            for commitment in commitments {
                for (weights, oods_row) in zip_strict(
                    commitment
                        .out_of_domain()
                        .weights(self.initial_num_variables()),
                    commitment.out_of_domain().rows(),
                ) {
                    for j in 0..num_polynomials {
                        if j >= polynomial_offset && j < oods_row.len() + polynomial_offset {
                            matrix.push(oods_row[j - polynomial_offset]);
                        } else {
                            matrix.push(verifier_state.prover_message()?);
                        }
                    }
                    all_weights.push(weights);
                }
                polynomial_offset += commitment.num_polynomials();
            }

            all_weights.extend(weights.iter().map(|&w| w.clone()));
            matrix.extend_from_slice(evaluations);
            (all_weights, matrix)
        };

        // Random linear combination of the polynomials.
        let polynomial_rlc_coeffs = geometric_challenge(verifier_state, num_polynomials);
        let mut prev_commitment = RoundCommitment::Initial {
            commitments,
            batching_weights: polynomial_rlc_coeffs.clone(),
        };

        // Random linear combination of the constraints.
        let constraint_rlc_coeffs: Vec<F> =
            geometric_challenge(verifier_state, constraint_weights.len());
        let mut round_constraints = vec![(constraint_rlc_coeffs.clone(), constraint_weights)];

        // Compute "The Sum"
        let mut the_sum = zip_strict(
            &constraint_rlc_coeffs,
            constraint_matrix.chunks_exact(num_polynomials),
        )
        .map(|(poly_coeff, row)| *poly_coeff * dot(&polynomial_rlc_coeffs, row))
        .sum();

        let mut round_folding_randomness = Vec::new();

        // Run initial sumcheck on batched polynomial with combined statement
        let folding_randomness = if constraint_rlc_coeffs.is_empty() {
            // There are no constraints yet, so we can skip the sumcheck.
            // (If we did run it, all sumcheck polynomials would be constant zero)
            assert_eq!(the_sum, F::ZERO);
            let folding_randomness =
                verifier_state.verifier_message_vec(self.initial_sumcheck.num_rounds);
            self.initial_sumcheck.round_pow.verify(verifier_state)?;
            MultilinearPoint(folding_randomness)
        } else {
            self.initial_sumcheck.verify(verifier_state, &mut the_sum)?
        };
        round_folding_randomness.push(folding_randomness);

        for (round_index, round_config) in self.round_configs.iter().enumerate() {
            // Receive commitment to the folded polynomial, plus out-of-domain constraints
            let commitment = round_config
                .irs_committer
                .receive_commitment(verifier_state)?;

            // Proof of work before in-domain challenges
            round_config.pow.verify(verifier_state)?;

            // Open the previous round's commitment, producing in-domain evaluations.
            let (in_domain, poly_rlc) = match prev_commitment {
                RoundCommitment::Initial {
                    commitments,
                    batching_weights,
                } => {
                    let in_domain = self.initial_committer.verify(verifier_state, commitments)?;
                    (in_domain.lift(self.embedding()), batching_weights)
                }
                RoundCommitment::Round { commitment } => {
                    let prev_round_config = &self.round_configs[round_index - 1];
                    let in_domain = prev_round_config
                        .irs_committer
                        .verify(verifier_state, &[&commitment])?;
                    (in_domain, vec![F::ONE])
                }
            };

            // Random linear combination of out- and in-domain constraints
            let constraint_weights = commitment
                .out_of_domain()
                .weights(round_config.initial_num_variables())
                .chain(in_domain.weights(round_config.initial_num_variables()))
                .collect::<Vec<_>>();
            let constraint_values = commitment
                .out_of_domain()
                .values(&[F::ONE])
                .chain(in_domain.values(&tensor_product(
                    &poly_rlc,
                    &round_folding_randomness.last().unwrap().coeff_weights(true),
                )))
                .collect::<Vec<_>>();
            let constraint_rlc_coeffs =
                geometric_challenge(verifier_state, constraint_weights.len());
            the_sum += dot(&constraint_rlc_coeffs, &constraint_values);
            round_constraints.push((constraint_rlc_coeffs, constraint_weights));

            // Sumcheck round
            let folding_randomness = round_config.sumcheck.verify(verifier_state, &mut the_sum)?;
            round_folding_randomness.push(folding_randomness);

            prev_commitment = RoundCommitment::Round { commitment };
        }

        // Final round (we receive the full polynomial instead of a commitment)
        let final_coefficients = CoefficientList::new(
            verifier_state.prover_messages_vec(self.final_sumcheck.initial_size)?,
        );

        // Final proof of work.
        self.final_pow.verify(verifier_state)?;

        // Open previous witness, as usual
        let (in_domain, poly_rlc) = match prev_commitment {
            RoundCommitment::Initial {
                commitments,
                batching_weights,
            } => {
                let in_domain = self.initial_committer.verify(verifier_state, commitments)?;
                (in_domain.lift(self.embedding()), batching_weights)
            }
            RoundCommitment::Round { commitment } => {
                let prev_round_config = &self.round_configs.last().unwrap();
                let in_domain = prev_round_config
                    .irs_committer
                    .verify(verifier_state, &[&commitment])?;
                (in_domain, vec![F::ONE])
            }
        };

        // Verify in-domain constraints directly
        for (weights, evals) in zip_strict(
            in_domain.weights(final_coefficients.num_variables()),
            in_domain.values(&tensor_product(
                &poly_rlc,
                &round_folding_randomness.last().unwrap().coeff_weights(true),
            )),
        ) {
            verify!(weights.evaluate(&final_coefficients) == evals);
        }

        // Final sumcheck
        let final_sumcheck_randomness = self.final_sumcheck.verify(verifier_state, &mut the_sum)?;
        round_folding_randomness.push(final_sumcheck_randomness.clone());

        // Final consistency check (shared with verify_zk)
        self.verify_final_consistency(
            verifier_state,
            &round_constraints,
            &round_folding_randomness,
            &final_coefficients,
            &final_sumcheck_randomness,
            the_sum,
        )
    }

    /// Verify a ZK WHIR opening proof.
    ///
    /// This verifies a proof generated by `prove_zk`. The verifier:
    /// 1. Reads blinding evaluations g(āᵢ) and reconstructs modified sums
    /// 2. Runs WHIR rounds, reconstructing virtual oracle values at each initial opening
    /// 3. Verifies helper polynomial evaluations via a nested WHIR proof
    /// 4. Checks the final sumcheck equation
    pub fn verify_zk<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        f_hat_commitments: &[&Commitment<F>],
        helper_commitment: &Commitment<F>,
        helper_config: &Config<F>,
        zk_params: &ZkParams,
        weights: &[&Weights<F>],
        evaluations: &[F],
    ) -> VerificationResult<(MultilinearPoint<F>, Vec<F>)>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
        [u8; 32]: Decoding<[H::U]>,
        U64: Codec<[H::U]>,
        Hash: ProverMessage<[H::U]>,
    {
        // ====================================================================
        // Phase 1: ZK transcript header — read blinding challenges and build
        //          modified evaluations for P = ρ·f + g
        // ====================================================================
        let num_polys = f_hat_commitments.len();
        let (beta, rho, modified_evaluations) =
            self.read_zk_header(verifier_state, weights, evaluations, num_polys)?;

        let polynomial_rlc_coeffs: Vec<F> =
            geometric_challenge(verifier_state, f_hat_commitments.len());
        let constraint_rlc_coeffs: Vec<F> = geometric_challenge(verifier_state, weights.len());
        let mut round_constraints: Vec<(Vec<F>, Vec<Weights<F>>)> = vec![(
            constraint_rlc_coeffs.clone(),
            weights.iter().map(|&w| w.clone()).collect(),
        )];

        let mut the_sum: F = zip_strict(
            &constraint_rlc_coeffs,
            modified_evaluations.chunks_exact(num_polys),
        )
        .map(|(weight_coeff, row)| *weight_coeff * dot(&polynomial_rlc_coeffs, row))
        .sum();

        let mut round_folding_randomness = Vec::new();

        let folding_randomness = if constraint_rlc_coeffs.is_empty() {
            assert_eq!(the_sum, F::ZERO);
            let fr = verifier_state.verifier_message_vec(self.initial_sumcheck.num_rounds);
            self.initial_sumcheck.round_pow.verify(verifier_state)?;
            MultilinearPoint(fr)
        } else {
            self.initial_sumcheck.verify(verifier_state, &mut the_sum)?
        };
        round_folding_randomness.push(folding_randomness);

        // ====================================================================
        // Phase 2: WHIR round loop
        // ====================================================================
        let mut prev_is_initial = true;
        let mut prev_round_commitment: Option<irs_commit::Commitment<F>> = None;

        for (round_index, round_config) in self.round_configs.iter().enumerate() {
            let commitment = round_config
                .irs_committer
                .receive_commitment(verifier_state)?;
            round_config.pow.verify(verifier_state)?;

            let num_variables = round_config.initial_num_variables();

            let (stir_weights, stir_values) = if prev_is_initial {
                self.verify_initial_zk_round(
                    verifier_state,
                    f_hat_commitments,
                    helper_commitment,
                    helper_config,
                    zk_params,
                    rho,
                    beta,
                    &commitment,
                    &round_folding_randomness,
                    num_variables,
                    &polynomial_rlc_coeffs,
                )?
            } else {
                self.verify_subsequent_round(
                    verifier_state,
                    round_index,
                    prev_round_commitment.as_ref().unwrap(),
                    &commitment,
                    &round_folding_randomness,
                    num_variables,
                )?
            };

            let stir_rlc_coeffs = geometric_challenge(verifier_state, stir_weights.len());
            the_sum += dot(&stir_rlc_coeffs, &stir_values);
            round_constraints.push((stir_rlc_coeffs, stir_weights));

            let folding_randomness = round_config.sumcheck.verify(verifier_state, &mut the_sum)?;
            round_folding_randomness.push(folding_randomness);

            prev_is_initial = false;
            prev_round_commitment = Some(commitment);
        }

        // ====================================================================
        // Phase 3: Final round — read polynomial, verify last commitment
        // ====================================================================
        let final_coefficients = CoefficientList::new(
            verifier_state.prover_messages_vec(self.final_sumcheck.initial_size)?,
        );
        self.final_pow.verify(verifier_state)?;

        self.verify_zk_final_opening(
            verifier_state,
            prev_is_initial,
            f_hat_commitments,
            helper_commitment,
            helper_config,
            zk_params,
            rho,
            beta,
            prev_round_commitment.as_ref(),
            &round_folding_randomness,
            &final_coefficients,
            &polynomial_rlc_coeffs,
        )?;

        // ====================================================================
        // Phase 4: Final sumcheck + consistency check
        // ====================================================================
        let final_sumcheck_randomness = self.final_sumcheck.verify(verifier_state, &mut the_sum)?;
        round_folding_randomness.push(final_sumcheck_randomness.clone());

        self.verify_final_consistency(
            verifier_state,
            &round_constraints,
            &round_folding_randomness,
            &final_coefficients,
            &final_sumcheck_randomness,
            the_sum,
        )
    }

    /// Read the ZK transcript header: β, g(āᵢ) evaluations, ρ.
    ///
    /// Returns `(beta, rho, modified_evaluations)` where
    /// modified_evaluations[i] = ρ·evaluations[i] + g_evals[i].
    fn read_zk_header<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        weights: &[&Weights<F>],
        evaluations: &[F],
        num_commitments: usize,
    ) -> VerificationResult<(F, F, Vec<F>)>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
    {
        let beta: F = verifier_state.verifier_message();
        let g_evals: Vec<F> =
            verifier_state.prover_messages_vec(weights.len() * num_commitments)?;
        let rho: F = verifier_state.verifier_message();

        let modified_evaluations: Vec<F> = zip_strict(evaluations, &g_evals)
            .map(|(&eval, &g_eval)| rho * eval + g_eval)
            .collect();

        Ok((beta, rho, modified_evaluations))
    }

    /// Verify the initial ZK round opening: verify f̂ commitment(s), helper evaluations,
    /// and reconstruct virtual oracle values.
    ///
    /// For N committed polynomials, opens all N f̂ commitments, verifies helper
    /// evaluations for each, and reconstructs combined virtual oracle values using
    /// the polynomial RLC coefficients.
    ///
    /// Returns `(stir_weights, stir_values)`.
    #[allow(clippy::too_many_arguments)]
    fn verify_initial_zk_round<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        f_hat_commitments: &[&Commitment<F>],
        helper_commitment: &Commitment<F>,
        helper_config: &Config<F>,
        zk_params: &ZkParams,
        rho: F,
        beta: F,
        commitment: &irs_commit::Commitment<F>,
        round_folding_randomness: &[MultilinearPoint<F>],
        num_variables: usize,
        polynomial_rlc_coeffs: &[F],
    ) -> VerificationResult<(Vec<Weights<F>>, Vec<F>)>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
        [u8; 32]: Decoding<[H::U]>,
        U64: Codec<[H::U]>,
        Hash: ProverMessage<[H::U]>,
    {
        let num_polys = f_hat_commitments.len();
        let in_domain_base = self
            .initial_committer
            .verify(verifier_state, f_hat_commitments)?;

        let virtual_values = self.verify_zk_helper_evaluations(
            verifier_state,
            &in_domain_base,
            helper_commitment,
            helper_config,
            zk_params,
            rho,
            beta,
            round_folding_randomness.last().unwrap(),
            num_polys,
            polynomial_rlc_coeffs,
        )?;
        let in_domain = in_domain_base.lift(self.embedding());

        let stir_weights: Vec<Weights<F>> = commitment
            .out_of_domain()
            .weights(num_variables)
            .chain(in_domain.weights(num_variables))
            .collect();
        let stir_values: Vec<F> = commitment
            .out_of_domain()
            .values(&[F::ONE])
            .chain(virtual_values)
            .collect();

        Ok((stir_weights, stir_values))
    }

    /// Verify a subsequent (non-initial) round opening.
    ///
    /// Returns `(stir_weights, stir_values)`.
    fn verify_subsequent_round<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        round_index: usize,
        prev_commitment: &irs_commit::Commitment<F>,
        commitment: &irs_commit::Commitment<F>,
        round_folding_randomness: &[MultilinearPoint<F>],
        num_variables: usize,
    ) -> VerificationResult<(Vec<Weights<F>>, Vec<F>)>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
        [u8; 32]: Decoding<[H::U]>,
        U64: Codec<[H::U]>,
        Hash: ProverMessage<[H::U]>,
    {
        let prev_round_config = &self.round_configs[round_index - 1];
        let in_domain = prev_round_config
            .irs_committer
            .verify(verifier_state, &[prev_commitment])?;

        let stir_weights: Vec<Weights<F>> = commitment
            .out_of_domain()
            .weights(num_variables)
            .chain(in_domain.weights(num_variables))
            .collect();
        let stir_values: Vec<F> = commitment
            .out_of_domain()
            .values(&[F::ONE])
            .chain(in_domain.values(&round_folding_randomness.last().unwrap().coeff_weights(true)))
            .collect();

        Ok((stir_weights, stir_values))
    }

    /// Verify the final commitment opening in ZK mode.
    ///
    /// Handles both the case where this is the initial commitment (no intermediate
    /// rounds) and the case where it's the last WHIR round commitment.
    /// For the initial case with N polynomials, opens all N f̂ commitments and
    /// verifies the batched virtual oracle.
    #[allow(clippy::too_many_arguments)]
    fn verify_zk_final_opening<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        prev_is_initial: bool,
        f_hat_commitments: &[&Commitment<F>],
        helper_commitment: &Commitment<F>,
        helper_config: &Config<F>,
        zk_params: &ZkParams,
        rho: F,
        beta: F,
        prev_round_commitment: Option<&irs_commit::Commitment<F>>,
        round_folding_randomness: &[MultilinearPoint<F>],
        final_coefficients: &CoefficientList<F>,
        polynomial_rlc_coeffs: &[F],
    ) -> VerificationResult<()>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
        [u8; 32]: Decoding<[H::U]>,
        U64: Codec<[H::U]>,
        Hash: ProverMessage<[H::U]>,
    {
        if prev_is_initial {
            let num_polys = f_hat_commitments.len();
            let in_domain_base = self
                .initial_committer
                .verify(verifier_state, f_hat_commitments)?;

            let virtual_values = self.verify_zk_helper_evaluations(
                verifier_state,
                &in_domain_base,
                helper_commitment,
                helper_config,
                zk_params,
                rho,
                beta,
                round_folding_randomness.last().unwrap(),
                num_polys,
                polynomial_rlc_coeffs,
            )?;

            let in_domain = in_domain_base.lift(self.embedding());
            for (weights, value) in zip_strict(
                in_domain.weights(final_coefficients.num_variables()),
                virtual_values,
            ) {
                verify!(weights.evaluate(final_coefficients) == value);
            }
        } else {
            let prev_round_config = self.round_configs.last().unwrap();
            let in_domain = prev_round_config
                .irs_committer
                .verify(verifier_state, &[prev_round_commitment.unwrap()])?;

            for (weights, evals) in zip_strict(
                in_domain.weights(final_coefficients.num_variables()),
                in_domain.values(&round_folding_randomness.last().unwrap().coeff_weights(true)),
            ) {
                verify!(weights.evaluate(final_coefficients) == evals);
            }
        }
        Ok(())
    }

    /// Verify the final consistency check: compute folding randomness, read deferred
    /// hints, evaluate weight functions, and check the final sumcheck equation.
    ///
    /// This is shared between `verify` and `verify_zk`.
    fn verify_final_consistency<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        round_constraints: &[(Vec<F>, Vec<Weights<F>>)],
        round_folding_randomness: &[MultilinearPoint<F>],
        final_coefficients: &CoefficientList<F>,
        final_sumcheck_randomness: &MultilinearPoint<F>,
        the_sum: F,
    ) -> VerificationResult<(MultilinearPoint<F>, Vec<F>)>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
    {
        let folding_randomness = MultilinearPoint(
            round_folding_randomness
                .iter()
                .rev()
                .flat_map(|poly| poly.0.iter().copied())
                .collect(),
        );

        let deferred: Vec<F> = verifier_state.prover_hint_ark()?;
        let mut deferred_iter = deferred.iter().copied();
        let mut weight_eval = F::ZERO;

        for (round, (weights_rlc_coeffs, round_weights)) in round_constraints.iter().enumerate() {
            let num_variables = round.checked_sub(1).map_or_else(
                || self.initial_num_variables(),
                |p| self.round_configs[p].initial_num_variables(),
            );
            let point = MultilinearPoint(folding_randomness.0[..num_variables].to_vec());
            for (rlc_coeff, w) in zip_strict(weights_rlc_coeffs, round_weights) {
                let eval = if w.deferred() {
                    let d = deferred_iter.next();
                    verify!(d.is_some());
                    d.unwrap()
                } else {
                    w.compute(&point)
                };
                weight_eval += *rlc_coeff * eval;
            }
        }
        verify!(deferred_iter.next().is_none());

        let poly_eval = final_coefficients.evaluate(final_sumcheck_randomness);
        verify!(poly_eval * weight_eval == the_sum);

        Ok((folding_randomness, deferred))
    }

    /// Verify the ZK initial commitment opening: verify [[f̂]], read + verify helper
    /// evaluations, and reconstruct virtual oracle constraint values.
    ///
    /// For N committed polynomials, reads N helper evaluation sets per gamma point,
    /// verifies them via a nested WHIR proof, then reconstructs per-polynomial virtual
    /// oracle values L_p(γ) and combines them via polynomial RLC.
    ///
    /// Returns the virtual oracle folded values for each query point (to use as
    /// STIR in-domain constraint values).
    #[allow(clippy::too_many_arguments)]
    fn verify_zk_helper_evaluations<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        in_domain_base: &irs_commit::Evaluations<F::BasePrimeField>,
        helper_commitment: &Commitment<F>,
        helper_config: &Config<F>,
        zk_params: &ZkParams,
        rho: F,
        beta: F,
        folding_randomness: &MultilinearPoint<F>,
        num_polys: usize,
        polynomial_rlc_coeffs: &[F],
    ) -> VerificationResult<Vec<F>>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
        [u8; 32]: Decoding<[H::U]>,
        U64: Codec<[H::U]>,
        Hash: ProverMessage<[H::U]>,
    {
        use crate::algebra::polynomials::fold::compute_fold;

        let embedding = self.embedding();
        let mu = zk_params.mu;
        let k = self.initial_committer.interleaving_depth;
        let num_rows = self.initial_committer.num_rows();
        let full_domain_size = num_rows * k;
        let fold_factor = k.trailing_zeros() as usize; // log2(k)

        // Get generators for domain structure
        let omega_full: F::BasePrimeField =
            ntt::generator(full_domain_size).expect("Full IRS domain should have primitive root");
        let omega_sub: F::BasePrimeField = self.initial_committer.generator();
        let zeta: F::BasePrimeField = omega_full.pow([num_rows as u64]); // k-th root of unity

        // Precompute inverses for compute_fold (lifted to extension field)
        let zeta_ext_inv: F = embedding
            .map(zeta)
            .inverse()
            .expect("coset generator invertible");
        let two_inv = F::from(2u64).inverse().expect("char ≠ 2");

        // Precompute sub-domain powers for index recovery
        let mut omega_powers = Vec::with_capacity(num_rows);
        let mut power = F::BasePrimeField::ONE;
        for _ in 0..num_rows {
            omega_powers.push(power);
            power *= omega_sub;
        }

        // Read helper evaluations from transcript, grouped per polynomial.
        // Prover sends: for each gamma, for each polynomial p:
        //   m_eval_p, ĝ₁(pow(γ))_p, ..., ĝμ(pow(γ))_p
        let q = in_domain_base.points.len();
        let mut helper_evals_per_poly: Vec<Vec<HelperEvaluations<F>>> =
            (0..num_polys).map(|_| Vec::with_capacity(q * k)).collect();
        let mut query_indices: Vec<usize> = Vec::with_capacity(q);

        for &alpha_base in &in_domain_base.points {
            let idx = omega_powers
                .iter()
                .position(|&p| p == alpha_base)
                .expect("Query point must be in IRS domain");
            query_indices.push(idx);
            let coset_offset = omega_full.pow([idx as u64]);

            for j in 0..k {
                let gamma_base = coset_offset * zeta.pow([j as u64]);
                let gamma: F = embedding.map(gamma_base);
                for p in 0..num_polys {
                    let m_eval: F = verifier_state.prover_message()?;
                    let g_hat_evals: Vec<F> = verifier_state.prover_messages_vec(mu)?;
                    helper_evals_per_poly[p].push(HelperEvaluations {
                        gamma,
                        m_eval,
                        g_hat_evals,
                    });
                }
            }
        }

        // Sample τ₂ (query-batching challenge)
        let tau2: F = verifier_state.verifier_message();

        // Construct batched eq weights (gammas are shared across polynomials)
        let beq_weights = Config::<F>::construct_batched_eq_weights(
            &helper_evals_per_poly[0],
            rho,
            tau2,
            zk_params.ell,
        );

        // Compute per-polynomial claims and collect evaluations
        // Layout: [m₁_claim, ĝ₁₁_claim, ..., ĝ₁μ_claim, m₂_claim, ĝ₂₁_claim, ..., ĝ₂μ_claim, ...]
        let mut all_evaluations: Vec<F> = Vec::with_capacity(num_polys * (1 + mu));
        for p in 0..num_polys {
            let (m_claim, g_hat_claims) =
                Config::<F>::compute_per_polynomial_claims(&helper_evals_per_poly[p], tau2);
            all_evaluations.push(m_claim);
            all_evaluations.extend_from_slice(&g_hat_claims);
        }

        let weight_refs: Vec<&Weights<F>> = vec![&beq_weights];

        // Verify helper WHIR proof (single batch commitment for all N×(μ+1) helper polys)
        helper_config.verify(
            verifier_state,
            &[helper_commitment],
            &weight_refs,
            &all_evaluations,
        )?;

        // Reconstruct virtual oracle values from IRS opening + verified helper evaluations.
        // For N polynomials: compute per-polynomial L_p(γ_j), RLC across polynomials,
        // then fold the combined coset values.
        let num_cols = in_domain_base.num_columns();
        let k_per_poly = k; // columns per committed polynomial (batch_size=1 for ZK)

        let virtual_values: Vec<F> = in_domain_base
            .points
            .iter()
            .enumerate()
            .map(|(qi, _)| {
                let idx = query_indices[qi];
                let coset_offset = omega_full.pow([idx as u64]);
                let coset_offset_ext_inv: F =
                    embedding.map(coset_offset).inverse().unwrap_or(F::ZERO);

                let row = &in_domain_base.matrix[qi * num_cols..(qi + 1) * num_cols];

                // Compute L_combined(γ_j) = Σ_p α_p · L_p(γ_j) for each coset element j
                let l_coset_values: Vec<F> = (0..k)
                    .map(|j| {
                        let gamma_base = coset_offset * zeta.pow([j as u64]);
                        let gamma_ext: F = embedding.map(gamma_base);

                        let mut l_combined = F::ZERO;
                        for p in 0..num_polys {
                            // f̂_p(γ_j) = Σ_{l=0}^{k-1} γ^l · embed(row[p*k + l])
                            let mut f_hat_p_at_gamma = F::ZERO;
                            let mut gamma_power = F::ONE;
                            for l in 0..k_per_poly {
                                f_hat_p_at_gamma +=
                                    gamma_power * embedding.map(row[p * k_per_poly + l]);
                                gamma_power *= gamma_ext;
                            }

                            // h_p(γ_j) from verified per-polynomial helper evaluations
                            let h_p_at_gamma =
                                helper_evals_per_poly[p][qi * k + j].compute_h_value(beta);

                            // L_p(γ_j) = ρ·f̂_p(γ_j) + h_p(γ_j)
                            let l_p = rho * f_hat_p_at_gamma + h_p_at_gamma;

                            l_combined += polynomial_rlc_coeffs[p] * l_p;
                        }
                        l_combined
                    })
                    .collect();

                // Fold the k combined coset values
                compute_fold(
                    &l_coset_values,
                    &folding_randomness.0,
                    coset_offset_ext_inv,
                    zeta_ext_inv,
                    two_inv,
                    fold_factor,
                )
            })
            .collect();

        Ok(virtual_values)
    }
}
