use ark_ff::FftField;

use super::{
    committer::ParsedCommitment,
    parameters::{RoundConfig, WhirConfig},
    statement::{Constraint, Statement, Weights},
};
use crate::{
    algebra::{
        embedding::{self, Embedding},
        mixed_dot,
        poly_utils::{coeffs::CoefficientList, multilinear::MultilinearPoint},
        tensor_product,
    },
    hash::Hash,
    protocols::{geometric_challenge::geometric_challenge, irs_commit, matrix_commit, sumcheck},
    transcript::{
        codecs::U64, Codec, Decoding, DuplexSpongeInterface, ProverMessage, VerificationResult,
        VerifierMessage, VerifierState,
    },
    type_info::Type,
    utils::{expand_randomness, zip_strict},
    verify,
    whir::utils::get_challenge_stir_queries,
};

pub struct Verifier<'a, F: FftField> {
    config: &'a WhirConfig<F>,
}

pub(crate) enum RoundCommitment<'a, F: FftField> {
    Initial {
        commitments: &'a [irs_commit::Commitment<F>],
        batching_weights: Vec<F>,
    },
    Round {
        matrix_commitment: matrix_commit::Commitment,
    },
}

impl<'a, F: FftField> Verifier<'a, F> {
    pub const fn new(params: &'a WhirConfig<F>) -> Self {
        Self { config: params }
    }

    /// Verify a WHIR proof.
    ///
    /// Returns the constraint evaluation point and the values of the deferred constraints.
    /// It is the callers responsibility to verify the deferred constraints.
    #[allow(clippy::too_many_lines)]
    pub fn verify<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        parsed_commitment: &ParsedCommitment<F>,
        statement: &Statement<F>,
    ) -> VerificationResult<(MultilinearPoint<F>, Vec<F>)>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
        [u8; 32]: Decoding<[H::U]>,
        U64: Codec<[H::U]>,
        Hash: ProverMessage<[H::U]>,
    {
        self.verify_batch(
            verifier_state,
            &[parsed_commitment.clone()],
            &[statement.clone()],
        )
    }

    /// Verify a batched WHIR proof for multiple commitments.
    ///
    /// This verifies a batch proof generated by `prove_batch`. The verifier reads the N×M
    /// constraint evaluation matrix from the transcript, samples the batching randomness γ,
    /// and reconstructs the combined constraints using RLC. Round 0 verifies openings in all
    /// N original commitment trees, while subsequent rounds verify the single batched polynomial.
    ///
    /// Returns the constraint evaluation point and values of deferred constraints.
    #[allow(clippy::too_many_lines)]
    pub fn verify_batch<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        parsed_commitments: &[ParsedCommitment<F>],
        statements: &[Statement<F>],
    ) -> VerificationResult<(MultilinearPoint<F>, Vec<F>)>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
        [u8; 32]: Decoding<[H::U]>,
        U64: Codec<[H::U]>,
        Hash: ProverMessage<[H::U]>,
    {
        assert!(!parsed_commitments.is_empty());
        assert_eq!(
            parsed_commitments.len() * self.config.initial_committer.num_polynomials,
            statements.len()
        );
        let embedding = self.config.initial_committer.embedding();

        // Step 1: Read the N×M constraint evaluation matrix from the transcript

        // Collect all constraint weights to determine matrix dimensions
        let mut all_constraints_info: Vec<(Weights<F>, bool)> = Vec::new();

        // OOD constraints from each commitment
        for commitment in parsed_commitments {
            for point in &commitment.commitment.out_of_domain().points {
                let ml_point = MultilinearPoint::expand_from_univariate(
                    *point,
                    self.config.mv_parameters.num_variables,
                );
                all_constraints_info.push((Weights::evaluation(ml_point), false));
            }
        }

        // Statement constraints
        for statement in statements {
            for constraint in &statement.constraints {
                all_constraints_info
                    .push((constraint.weights.clone(), constraint.defer_evaluation));
            }
        }

        // Construct the N×M evaluation matrix.
        let num_polynomials =
            parsed_commitments.len() * self.config.initial_committer.num_polynomials;
        let num_constraints = all_constraints_info.len();
        let mut constraint_evals_matrix = vec![None; num_polynomials * num_constraints];
        // Add the claimed OODs values
        let mut polynomial_offset = 0;
        let mut constraint_offset = 0;
        for commitment in parsed_commitments.iter() {
            for row in commitment.commitment.out_of_domain().rows() {
                let mut index = polynomial_offset + constraint_offset;
                for value in row {
                    assert!(constraint_evals_matrix[index].is_none());
                    constraint_evals_matrix[index] = Some(*value);
                    index += num_constraints;
                }
                constraint_offset += 1;
            }
            polynomial_offset +=
                commitment.commitment.out_of_domain().num_columns() * num_constraints;
        }
        // Add the claimed statement values
        let mut index = parsed_commitments
            .iter()
            .map(|c| c.commitment.out_of_domain().num_points())
            .sum::<usize>();
        for statement in statements.iter() {
            for constraint in statement.constraints.iter() {
                assert!(constraint_evals_matrix[index].is_none());
                constraint_evals_matrix[index] = Some(constraint.sum);
                index += 1;
            }
            index += num_constraints;
        }
        // Complete using prover claimed values
        for cell in &mut constraint_evals_matrix {
            if cell.is_none() {
                *cell = Some(verifier_state.prover_message()?);
            }
        }
        let constraint_evals_matrix: Vec<F> = constraint_evals_matrix
            .into_iter()
            .map(|e| e.unwrap())
            .collect();
        dbg!(&constraint_evals_matrix);
        // Reinterpret as rows for easier indexing: rows = num_polynomials, cols = num_constraints
        let constraint_evals_matrix: Vec<&[F]> = constraint_evals_matrix
            .chunks_exact(num_constraints)
            .collect();

        // Step 2: Sample batching randomness γ (cryptographically bound to matrix)
        let batching_weights = geometric_challenge(verifier_state, num_polynomials);

        let irs_commitments = parsed_commitments
            .iter()
            .map(|c| c.commitment.clone())
            .collect::<Vec<_>>();
        let mut prev_commitment = RoundCommitment::Initial {
            commitments: &irs_commitments,
            batching_weights: batching_weights.clone(),
        };

        let mut round_constraints = Vec::new();
        let mut round_folding_randomness = Vec::new();
        let mut claimed_sum = F::ZERO;

        // Step 3: Reconstruct combined constraints using RLC of the evaluation matrix
        // For each constraint j: combined_eval[j] = Σᵢ γⁱ·eval[i][j]
        if self.config.initial_statement {
            let mut all_constraints = Vec::new();

            for (constraint_idx, (weights, defer_evaluation)) in
                all_constraints_info.into_iter().enumerate()
            {
                let mut combined_eval = F::ZERO;
                for (row, weight) in batching_weights.iter().enumerate() {
                    combined_eval += *weight * constraint_evals_matrix[row][constraint_idx];
                }

                all_constraints.push(Constraint {
                    weights,
                    sum: combined_eval,
                    defer_evaluation,
                });
            }

            let combination_randomness =
                self.combine_constraints(verifier_state, &mut claimed_sum, &all_constraints)?;
            round_constraints.push((combination_randomness, all_constraints));

            // Initial sumcheck on the combined constraints
            let config = sumcheck::Config {
                field: Type::new(),
                initial_size: 1 << self.config.folding_factor.at_round(0), // Not used
                rounds: vec![
                    sumcheck::RoundConfig {
                        pow: self.config.starting_folding_pow
                    };
                    self.config.folding_factor.at_round(0)
                ],
            };
            let folding_randomness = config.verify(verifier_state, &mut claimed_sum)?;
            round_folding_randomness.push(folding_randomness);
        } else {
            for commitment in parsed_commitments {
                assert_eq!(commitment.commitment.out_of_domain().points.len(), 0);
            }
            for statement in statements {
                assert!(statement.constraints.is_empty());
            }
            round_constraints.push((vec![], vec![]));

            let mut folding_randomness = vec![F::ZERO; self.config.folding_factor.at_round(0)];
            for randomness in &mut folding_randomness {
                *randomness = verifier_state.verifier_message();
            }
            round_folding_randomness.push(MultilinearPoint(folding_randomness));

            self.config.starting_folding_pow.verify(verifier_state)?;
        }

        for round_index in 0..self.config.n_rounds() {
            let round_params = &self.config.round_configs[round_index];

            let matrix_commitment = round_params
                .matrix_committer
                .receive_commitment(verifier_state)?;
            let ood_points: Vec<F> = verifier_state.verifier_message_vec(round_params.ood_samples);
            let ood_answers: Vec<F> = (0..round_params.ood_samples)
                .map(|_| verifier_state.prover_message::<F>())
                .collect::<Result<Vec<_>, _>>()?;
            let oods_constraints =
                ood_points
                    .iter()
                    .zip(ood_answers.iter())
                    .map(|(point, answer)| Constraint {
                        weights: Weights::univariate(*point, round_params.num_variables),
                        sum: *answer,
                        defer_evaluation: false,
                    });

            round_params.pow.verify(verifier_state)?;

            let in_domain_constraints = match prev_commitment {
                RoundCommitment::Initial {
                    commitments,
                    batching_weights,
                } => {
                    let as_refs = commitments.iter().map(|c| c).collect::<Vec<_>>();
                    let in_domain = self
                        .config
                        .initial_committer
                        .verify(verifier_state, &as_refs)?;
                    let weights = tensor_product(
                        &batching_weights,
                        &round_folding_randomness.last().unwrap().coeff_weights(true),
                    );
                    in_domain.constraints(embedding, &weights, round_params.num_variables)
                }
                RoundCommitment::Round { matrix_commitment } => self.verify_stir_challenges(
                    round_index,
                    verifier_state,
                    round_params,
                    &self.config.round_configs[round_index - 1].matrix_committer,
                    &matrix_commitment,
                    F::ZERO,
                    round_folding_randomness.last().unwrap(),
                )?,
            };

            let constraints: Vec<Constraint<F>> = oods_constraints
                .into_iter()
                .chain(in_domain_constraints.into_iter())
                .collect();
            let combination_randomness =
                self.combine_constraints(verifier_state, &mut claimed_sum, &constraints)?;
            round_constraints.push((combination_randomness.clone(), constraints));

            let config = sumcheck::Config {
                field: Type::new(),
                initial_size: 1 << self.config.folding_factor.at_round(round_index + 1), // Not used
                rounds: vec![
                    sumcheck::RoundConfig {
                        pow: round_params.folding_pow
                    };
                    self.config.folding_factor.at_round(round_index + 1)
                ],
            };
            let folding_randomness = config.verify(verifier_state, &mut claimed_sum)?;
            round_folding_randomness.push(folding_randomness);

            prev_commitment = RoundCommitment::Round { matrix_commitment };
        }

        // Final round (same as regular verify)
        let mut final_coefficients = vec![F::ZERO; 1 << self.config.final_sumcheck_rounds];
        for coeff in &mut final_coefficients {
            *coeff = verifier_state.prover_message()?;
        }
        let final_coefficients = CoefficientList::new(final_coefficients);

        self.config.final_pow.verify(verifier_state)?;

        let in_domain_constraints = match prev_commitment {
            RoundCommitment::Initial {
                commitments,
                batching_weights,
            } => {
                let num_variables = self.config.mv_parameters.num_variables
                    - self.config.folding_factor.at_round(0);
                let as_refs = commitments.iter().map(|c| c).collect::<Vec<_>>();
                let in_domain = self
                    .config
                    .initial_committer
                    .verify(verifier_state, &as_refs)?;
                let weights = tensor_product(
                    &batching_weights,
                    &round_folding_randomness.last().unwrap().coeff_weights(true),
                );
                in_domain.constraints(embedding, &weights, num_variables)
            }
            RoundCommitment::Round { matrix_commitment } => self.verify_stir_challenges(
                self.config.n_rounds(),
                verifier_state,
                &self.config.final_round_config(),
                &self.config.round_configs.last().unwrap().matrix_committer,
                &matrix_commitment,
                F::ZERO,
                round_folding_randomness.last().unwrap(),
            )?,
        };

        verify!(in_domain_constraints
            .iter()
            .all(|c| c.verify(&final_coefficients)));

        let config = sumcheck::Config {
            field: Type::new(),
            initial_size: 1 << self.config.final_sumcheck_rounds, // Not used
            rounds: vec![
                sumcheck::RoundConfig {
                    pow: self.config.final_folding_pow
                };
                self.config.final_sumcheck_rounds
            ],
        };
        let final_sumcheck_randomness = config.verify(verifier_state, &mut claimed_sum)?;
        round_folding_randomness.push(final_sumcheck_randomness.clone());

        // Compute folding randomness across all rounds
        let folding_randomness = MultilinearPoint(
            round_folding_randomness
                .into_iter()
                .rev()
                .flat_map(|poly| poly.0.into_iter())
                .collect(),
        );

        // Compute evaluation of weights in folding randomness
        let deferred: Vec<F> = verifier_state.prover_hint_ark()?;
        let evaluation_of_weights =
            self.eval_constraints_poly(&round_constraints, &deferred, folding_randomness.clone());

        // Check the final sumcheck evaluation
        let final_value = final_coefficients.evaluate(&final_sumcheck_randomness);
        verify!(claimed_sum == evaluation_of_weights * final_value);

        Ok((folding_randomness, deferred))
    }

    /// Create a random linear combination of constraints and add it to the claim.
    /// Returns the randomness used.
    pub fn combine_constraints<H>(
        &self,
        verifier_state: &mut VerifierState<'_, H>,
        claimed_sum: &mut F,
        constraints: &[Constraint<F>],
    ) -> VerificationResult<Vec<F>>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
        [u8; 32]: Decoding<[H::U]>,
        U64: Codec<[H::U]>,
        Hash: ProverMessage<[H::U]>,
    {
        assert!(constraints
            .windows(2)
            .all(|w| w[0].weights.num_variables() == w[1].weights.num_variables()));

        let combination_randomness_gen = verifier_state.verifier_message();
        let combination_randomness =
            expand_randomness(combination_randomness_gen, constraints.len());
        *claimed_sum += constraints
            .iter()
            .zip(&combination_randomness)
            .map(|(c, rand)| c.sum * rand)
            .sum::<F>();

        Ok(combination_randomness)
    }

    /// Verify a STIR challenges against a commitment and return the constraints.
    #[allow(clippy::too_many_arguments)] // To be replaced with irs_commit
    pub fn verify_stir_challenges<H>(
        &self,
        round_index: usize,
        verifier_state: &mut VerifierState<'_, H>,
        params: &RoundConfig<F>,
        committer: &matrix_commit::Config<F>,
        matrix_commitment: &matrix_commit::Commitment,
        batching_randomness: F,
        folding_randomness: &MultilinearPoint<F>,
    ) -> VerificationResult<Vec<Constraint<F>>>
    where
        H: DuplexSpongeInterface,
        F: Codec<[H::U]>,
        u8: Decoding<[H::U]>,
        [u8; 32]: Decoding<[H::U]>,
        U64: Codec<[H::U]>,
        Hash: ProverMessage<[H::U]>,
    {
        let stir_challenges_indexes = get_challenge_stir_queries(
            verifier_state,
            params.domain_size,
            params.folding_factor,
            params.num_queries,
        );

        // Always open against the single batched commitment
        let mut answers: Vec<F> = verifier_state.prover_hint_ark()?;
        committer.verify(
            verifier_state,
            matrix_commitment,
            &stir_challenges_indexes,
            &answers,
        )?;

        // If this is the first round and batching > 1, RLC per leaf to fold_size
        if round_index == 0 && self.config.batch_size > 1 {
            let fold_size = 1 << params.folding_factor;
            answers = crate::whir::utils::rlc_batched_leaves(
                &answers,
                fold_size,
                self.config.batch_size,
                batching_randomness,
            );
        }

        // Compute STIR Constraints
        let folds: Vec<F> = answers
            .chunks_exact(1 << params.folding_factor)
            .map(|answers| CoefficientList::new(answers.to_vec()).evaluate(folding_randomness))
            .collect();

        let stir_constraints = stir_challenges_indexes
            .iter()
            .map(|&index| params.exp_domain_gen.pow([index as u64]))
            .zip(&folds)
            .map(|(point, &value)| Constraint {
                weights: Weights::univariate(point, params.num_variables),
                sum: value,
                defer_evaluation: false,
            })
            .collect();

        Ok(stir_constraints)
    }

    /// Evaluate the random linear combination of constraints in `point`.
    fn eval_constraints_poly(
        &self,
        constraints: &[(Vec<F>, Vec<Constraint<F>>)],
        deferred: &[F],
        mut point: MultilinearPoint<F>,
    ) -> F {
        let mut num_variables = self.config.mv_parameters.num_variables;
        let mut deferred = deferred.iter().copied();
        let mut value = F::ZERO;

        for (round, (randomness, constraints)) in constraints.iter().enumerate() {
            assert_eq!(randomness.len(), constraints.len());
            if round > 0 {
                num_variables -= self.config.folding_factor.at_round(round - 1);
                point = MultilinearPoint(point.0[..num_variables].to_vec());
            }
            value += constraints
                .iter()
                .zip(randomness)
                .map(|(constraint, &randomness)| {
                    let value = if constraint.defer_evaluation {
                        deferred.next().unwrap()
                    } else {
                        constraint.weights.compute(&point)
                    };
                    value * randomness
                })
                .sum::<F>();
        }
        value
    }
}
